baseurl = "http://hansjoerg.netlify.com/"
title = "It was simple."
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Hansjörg Plieninger"
disqusShortname = "hansjoergplieninger"
# googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
math = true

[Author]
    name = "Hansjörg Plieninger"
    # profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "IT WAS SIMPLE"
    description = "Data science, psychology, R, blog by Hansjörg Plieninger"
    # github = "https://github.com/XXX"
    # gitlab = "https://gitlab.com/XXX"
    # linkedin = "https://linkedin.com/in/XXX/"
    # gplus = "https://google.com/+XXX"
    # twitter = "https://twitter.com/XXX"
    stackoverflow = "https://stackoverflow.com/users/2563804/hplieninger"
    # email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex", "Stan"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

[Permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
